# Generated by Django 2.2.19 on 2023-04-11 10:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_auto_20230410_2152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favoutrite',
            new_name='Favorite',
        ),
    ]
