# Generated by Django 2.2.16 on 2023-04-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230328_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('name',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.RemoveConstraint(
            model_name='favoutrite',
            name='unique_favourite',
        ),
        migrations.AddConstraint(
            model_name='favoutrite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_favourite_recipe'),
        ),
    ]
